Models/Question.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wenba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int id { get; set; }
        public string QuestionTitle { get; set; }
        public string QuestionDesc { get; set; }
        public string QuestionType { get; set; }
        public string QuestionNum { get; set; }
        public int CourseId { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public int LastUpdatedBy { get; set; }
        public string Attribute1 { get; set; }
        public string Attribute2 { get; set; }
        public string Attribute3 { get; set; }
        public string Attribute4 { get; set; }
        public string Attribute5 { get; set; }
        public string Attribute6 { get; set; }
        public string Attribute7 { get; set; }
        public string Attribute8 { get; set; }
        public string Attribute9 { get; set; }
        public string Attribute10 { get; set; }
        public string Status { get; set; }
    }
}

Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Wenba.Controllers
{
    public class IndexController : Controller
    {
        // GET: Index
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/QuestionsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Wenba.BLL;
using Wenba.Filters;
using Wenba.Models;
using Wenba.ViewModels;

namespace Wenba.Controllers
{
    [AuthorizationAttribute]
    public class QuestionsController : Controller
    {
        private WenbaDBContext db = new WenbaDBContext();

        [CustAuthorize("A", "M")]
        // GET: Questions
        public ActionResult Index(string ProjectId, string CourseId, string QuestionDesc, int? page)
        {
            //初始化项目名称列表
            List<SelectListItem> projectList = new List<SelectListItem>();
            //根据用户身份做判断
            List<Project> pList = new List<Project>();
            if (UserLogin.userroles.Contains("M"))
            {
                int userid = Convert.ToInt32(UserLogin.userid);
                var user = db.Users.Where(x => x.id == userid).FirstOrDefault();
                var pros = from Projects in db.Projects
                           where Projects.ManagerId == user.PersonId
                           select Projects;
                pList = pros.ToList();
            }
            else
            {
                pList = db.Projects.ToList();
            }

            foreach (var item in pList)
            {
                SelectListItem listItem = new SelectListItem();
                listItem.Text = item.ProjectName;
                listItem.Value = item.id.ToString();
                projectList.Add(listItem);
            }
            ViewData["ProjectList"] = projectList;
            if (String.IsNullOrEmpty(ProjectId))
            {
                List<SelectListItem> courseList = new List<SelectListItem>();
                ViewData["CouserList"] = courseList;
            }
            else
            {

                BindCourse(ProjectId);
            }

            //List<Question> questionList = db.Questions.OrderByDescending(c => c.CourseId).ThenBy(c => c.QuestionNum).ToList();
            //根据用户身份做判断
            List<Question> questionList = new List<Question>();
            if (UserLogin.userroles.Contains("M"))
            {
                int userid = Convert.ToInt32(UserLogin.userid);
                var user = db.Users.Where(x => x.id == userid).FirstOrDefault();
                var questions = from Questions in db.Questions
                                join Courses in db.Courses on Questions.CourseId equals Courses.id
                                join Projects in db.Projects on Courses.ProjectId equals Projects.id
                                where Projects.ManagerId == user.PersonId
                                select Questions;
                questionList = questions.OrderBy(c => c.QuestionNum).ToList();
                //questionList = questions.ToList();

            }
            else
            {
                //questionList = db.Questions.OrderByDescending(c => c.CourseId).ThenBy(c => c.QuestionNum).ToList();
                questionList = db.Questions.OrderByDescending(c => c.id).ToList();
            }

            List<CompositeQuestion> qquestionList = new List<CompositeQuestion>();

            foreach (var question in questionList)
            {
                CompositeQuestion qquestion = new CompositeQuestion();
                qquestion.Question = question;
                //与课程表关联
                Course course = db.Courses.FirstOrDefault(m => m.id == question.CourseId);
                qquestion.Course = course;

                //通过课程与项目表关联
                Project project = db.Projects.FirstOrDefault(p => p.id == course.ProjectId);
                qquestion.Project = project;

                qquestionList.Add(qquestion);
            }


            //第几页
            int pageNumbers = page ?? 1;
            //每页显示多少条
            int pageSizes = int.Parse(ConfigurationManager.AppSettings["pageSize"]);

            //筛选条件
            if (!String.IsNullOrEmpty(ProjectId) && ProjectId != "所有项目")
            {
                qquestionList = qquestionList.Where(x => x.Course.ProjectId.Equals(Convert.ToInt32(ProjectId))).ToList();
            }
            if (!String.IsNullOrEmpty(CourseId) && CourseId != "所有课程")
            {
                qquestionList = qquestionList.Where(x => x.Course.id.Equals(Convert.ToInt32(CourseId))).ToList();
            }

            if (!String.IsNullOrEmpty(QuestionDesc))
            {
                qquestionList = qquestionList.Where(x => x.Question.QuestionDesc.Contains(QuestionDesc)).ToList();
            }

            //通过ToPagedList扩展方法进行分页
            IPagedList<CompositeQuestion> pagedList = qquestionList.ToPagedList(pageNumbers, pageSizes);

            //将分页处理后的列表传给View
            this.ViewData["ProjectId"] = ProjectId;
            this.ViewData["CourseId"] = CourseId;
            this.ViewData["QuestionDesc"] = QuestionDesc;

            return View(pagedList);

            //return View(db.Questions.ToList());
        }

        // GET: Questions/Details/5
        [CustAuthorize("A", "M")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }

            CompositeQuestion qquestion = new CompositeQuestion();
            qquestion.Question = question;
            Course course = db.Courses.FirstOrDefault(m => m.id == question.CourseId);
            qquestion.Course = course;
            Project project = db.Projects.FirstOrDefault(p => p.id == course.ProjectId);
            qquestion.Project = project;

            return View(qquestion);


        }


        //联动 绑定课程
        public JsonResult BindCourse(string id)
        {
            List<SelectListItem> courseList = new List<SelectListItem>();
            int projectId = Convert.ToInt32(id);
            var list = from s in db.Courses.Where(c => c.ProjectId.Equals(projectId)).AsEnumerable()
                       select new SelectListItem
                       {
                           Value = s.id.ToString(),
                           Text = s.CourseName
                       };
            foreach (var item in list)
            {
                SelectListItem couserItem = new SelectListItem();
                couserItem.Text = item.Text;
                couserItem.Value = item.Value;
                courseList.Add(couserItem);
            }
            ViewData["CouserList"] = courseList;
            return Json(list.ToList());

        }


        // GET: Questions/Create
        [CustAuthorize("A", "M")]
        public ActionResult Create()
        {
            //初始化项目名称列表
            List<SelectListItem> projectList = new List<SelectListItem>();
            //根据用户身份做判断
            List<Project> pList = new List<Project>();
            if (UserLogin.userroles.Contains("M"))
            {
                int userid = Convert.ToInt32(UserLogin.userid);
                var user = db.Users.Where(x => x.id == userid).FirstOrDefault();
                var pros = from Projects in db.Projects
                           where Projects.ManagerId == user.PersonId
                           select Projects;
                pList = pros.ToList();
            }
            else
            {
                pList = db.Projects.ToList();
            }

            foreach (var item in pList)
            {
                SelectListItem listItem = new SelectListItem();
                listItem.Text = item.ProjectName;
                listItem.Value = item.id.ToString();
                projectList.Add(listItem);
            }
            ViewData["ProjectList"] = projectList;

            return View();
        }


        //// POST: Questions/Create  单个添加
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "id,QuestionTitle,QuestionDesc,QuestionType,QuestionNum,CourseId,Comments,CreatedBy,CreationDate,LastUpdateDate,LastUpdatedBy,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,Status")] Question question)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Questions.Add(question);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(question);
        //}


        // POST: Questions/Create 批量添加
        [CustAuthorize("A", "M")]
        [HttpPost]
        public ActionResult Create(QuestionsMassVM questions)
        {
            //初始化项目名称列表
            List<SelectListItem> projectList = new List<SelectListItem>();
            //根据用户身份做判断
            List<Project> pList = new List<Project>();
            if (UserLogin.userroles.Contains("M"))
            {
                int userid = Convert.ToInt32(UserLogin.userid);
                var user = db.Users.Where(x => x.id == userid).FirstOrDefault();
                var pros = from Projects in db.Projects
                           where Projects.ManagerId == user.PersonId
                           select Projects;
                pList = pros.ToList();
            }
            else
            {
                pList = db.Projects.ToList();
            }

            foreach (var item in pList)
            {
                SelectListItem listItem = new SelectListItem();
                listItem.Text = item.ProjectName;
                listItem.Value = item.id.ToString();
                projectList.Add(listItem);
            }
            ViewData["ProjectList"] = projectList;

            List<Question> quests = new List<Question>();

            for (int i = 0; i < questions.QuestionDesc.Count; i++)
            {

Views/Questions/Create.cshtml
@model Wenba.ViewModels.QuestionsMassVM
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>添加</h2>


@using (Html.BeginForm("Create", "Questions", FormMethod.Post))
{
    @Html.AntiForgeryToken()




        <div class="form-horizontal">
            <h4>Question</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="layui-form-item">
                <label class="layui-form-label">项目名称</label>
                <div class="layui-input-block">
                    @*@Html.DropDownList("ProjectId", new SelectList(ViewBag.ProjectList, "projectId", "projectName"), "所有项目", new { @onchange = "GetProjectId(this.value)" })*@
                    @Html.DropDownList("ProjectId", ViewData["ProjectList"] as List<SelectListItem>, "请选择项目", new { @onchange = "GetProjectId(this.value)" })
                    @Html.DropDownListFor(n => n.CourseId, new SelectList(Enumerable.Empty<SelectListItem>(), "courseId", "courseName"), "请先选择项目")
                </div>
            </div>

            <div class="form-group layui-form">
                类别
                <div class="col-md-10">
                    @Html.DropDownList("QuestionType", new List<SelectListItem>(){ new SelectListItem() { Text="问题",Value="Q"}
                                                                                  ,new SelectListItem() { Text="通知",Value="N"} })
                    @Html.ValidationMessageFor(model => model.QuestionType, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                创建人
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                创建时间
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                最近更新人
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastUpdatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastUpdatedBy, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                最近更新时间
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastUpdateDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastUpdateDate, "", new { @class = "text-danger" })
                </div>
            </div>*@
       

            <br />
            <br />
            <input type="button" value="新增" onclick="createRow()" class="layui-btn">
            <input type="button" value="删除" onclick="delRow()" class="layui-btn layui-btn-danger">
            

            <table name="editTable" id="editTable" class="table-hover gridtable">
                <tr>
                    <th style="width:5%">选择</th>
                    <th style="width:5%">编号</th>
                    <th style="width:60%">内容</th>
                    <th style="width:20%">备注</th>
                </tr>

                <tbody id="tbody"></tbody>
            </table>

            

            <br />


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input id="saveBtn" type="submit" value="保存" class="layui-btn layui-btn-normal" onclick="saveQues()" />
                </div>

                <div>
                    <label>@ViewBag.ErrorMsg</label>
                </div>

            </div>
        </div>

}

<div>
    @Html.ActionLink("返回列表", "Index")
</div>

<script>
    //获取项目id 再给子下拉框赋值
    function GetProjectId(id) {
        if (id == null) {

            $("#CourseId").empty().append("<option>请选择项目</option>");
            return;
        }
        else {
            $("#CourseId").empty();
            $.ajax({
                url: "/Questions/BindCourse/" + id,
                type: "post",
                success: function (data) {
                    $(data).each(function () {
                        $("#CourseId").append("<option value='" + this.Value + "'>" + this.Text + "</option>")
                    })
                }

            })
        }
        
    }

    //动态生成表格
    function createRow() {
        var editTable = document.getElementById("tbody");
        var tr = document.createElement("tr");
        var td0 = document.createElement("td");
        var checkbox = document.createElement("input");
        
        
        checkbox.type = "checkbox";
        checkbox.name = "checkRow";
        td0.appendChild(checkbox);
        td0.className = "checkCenter";
        var td1 = document.createElement("td");
        td1.innerHTML = "<input type='text' class='quesInfo QuestionNum' name='QuestionNum' >";

        var td2 = document.createElement("td");
        td2.innerHTML = "<input type='text' class='quesInfo' name='QuestionDesc' >";

        var td3 = document.createElement("td");
        td3.innerHTML = "<input type='text' class='quesInfo' name='Comments' >";

        tr.appendChild(td0);
        tr.appendChild(td1);
        tr.appendChild(td2);
        tr.appendChild(td3);
        editTable.appendChild(tr);
    }

    function delRow() {
        var editTable = document.getElementById("tbody");
       
       if (confirm("确认删除所选?")) {
            var checkboxs = document.getElementsByName("checkRow");
            for (var i = 0; i < checkboxs.length; i++) {
                if (checkboxs[i].checked) {
                    var n = checkboxs[i].parentNode.parentNode;
                    editTable.removeChild(n);
                    i--;
                }
            }

        }
    }

    function saveQues() {
       
        var checkQ = $(".QuestionNum").val();
        if (checkQ.length >= 4) {
            alert("编号长度应不大于三位数！");
            return fasle;
        }
    }
    
</script>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Questions/Delete.cshtml
@model Wenba.Models.Question

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h3>确定删除该条问题吗</h3>
<div>
    <hr />
    <h3>问题内容:@Html.DisplayFor(model => model.QuestionDesc)</h3>
    

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="margin-top:20px">
            <input type="submit" value="删除" class="layui-btn layui-btn-danger" /> |
            @Html.ActionLink("返回列表", "Index")
        </div>
    }
</div>

Views/Questions/Details.cshtml
@model Wenba.ViewModels.CompositeQuestion

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>问题或通知详情</h2>

<div class="shared-detail">
    <h4>Question</h4>
    <hr />
    <table class="dl-horizontal">

        <tr>
            <th>内容</th>
            <td>@Html.DisplayFor(model => model.Question.QuestionDesc)</td>
        </tr>
        <tr>
            <th>编号</th>
            <td>@Html.DisplayFor(model => model.Question.QuestionNum)</td>
        </tr>
        <tr>
            <th>项目名称</th>
            <td>@Html.DisplayFor(model => model.Project.ProjectName)</td>
        </tr>
        <tr>
            <th>课程名称</th>
            <td>@Html.DisplayFor(model => model.Course.CourseName)</td>
        </tr>
        <tr>
            <th>备注</th>
            <td>@Html.DisplayFor(model => model.Question.Comments)</td>
        </tr>
        <tr>
            <th>状态</th>
            <td>
                @if (Model.Question.Status.Contains("O"))
            {
                    @("已发布")
                }
                else
                {
                    @("未发布")
                }
            </td>
        </tr>

    </table>
</div>
<p>
    @if (Model.Question.Status.Contains("C"))
    {
        @Html.ActionLink("编辑", "Edit", new { id = Model.Question.id })
    }

    @Html.ActionLink("返回列表", "Index")
</p>

Views/Questions/Edit.cshtml
@model Wenba.Models.Question

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>编辑</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal layui-form">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)



        <div class="form-group">
            内容
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuestionDesc, new { htmlAttributes = new { @class = "form-control layui-input" } })
                @Html.ValidationMessageFor(model => model.QuestionDesc, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            编号
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuestionNum, new { htmlAttributes = new { @class = "form-control layui-input" } })
                @Html.ValidationMessageFor(model => model.QuestionNum, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            备注
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control layui-input" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>



        @*<div class="form-group">
            最近更新时间
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastUpdateDate, new { htmlAttributes = new { @class = "form-control layui-input" } })
                @Html.ValidationMessageFor(model => model.LastUpdateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            最近更新人
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastUpdatedBy, new { htmlAttributes = new { @class = "form-control layui-input" } })
                @Html.ValidationMessageFor(model => model.LastUpdatedBy, "", new { @class = "text-danger" })
            </div>
        </div>*@


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="提交" class="layui-btn layui-btn-normal" />
            </div>
        </div>
        
    </div>
}

<div>
    @Html.ActionLink("返回列表", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Questions/Index.cshtml
@model IPagedList<Wenba.ViewModels.CompositeQuestion>

@using PagedList.Mvc;
@using PagedList;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //int rownum = 1;
    //if (Model.IsFirstPage)
    //{
    //    rownum = 1;
    //}
    //else
    //{
    //    rownum = Model.PageSize * (Model.PageNumber - 1) + 1;
    //}

    var CourseId = ViewData["CourseId"];
    var ProjectId = ViewData["ProjectId"];
    var QuestionDesc = ViewData["QuestionDesc"];
}
<link href="~/Content/PagedList.css" rel="stylesheet" />



<div class="User-wrapper">
    <div class="item-module">
        <div class="item-title">
            <img src="~/Content/images/icon_project2.png" />
            <span>问题列表</span>
        </div>
        <form action="~/Questions/Index" method="post" name="form1" id="form1">
            <div class="layui-form-item inline-show item-filter">
                <label class="layui-form-label">项目名称</label>
                <div class="layui-input-block">

                    @Html.DropDownList("ProjectId", ViewData["ProjectList"] as List<SelectListItem>, "所有项目", new { @onchange = "GetProjectId(this.value)" })
                </div>
            </div>

            <div class="layui-form-item inline-show item-filter">
                <label class="layui-form-label">课程名称</label>
                <div class="layui-input-block">

                    @*@Html.DropDownList("CourseId", ViewData["CourseList"] as List<SelectListItem>, "所有课程")*@
                    @Html.DropDownList("CourseId", ViewData["CouserList"] as List<SelectListItem>, "所有课程", "courseName")

                </div>
            </div>

            <div class="layui-form-item inline-show item-filter">
                <label class="layui-form-label">问题内容</label>
                <div class="layui-input-block">
                    <input type="text" name="QuestionDesc" autocomplete="off" class="layui-input" value="@QuestionDesc">
                </div>
            </div>
            <div class="layui-form-item inline-show item-filter">
                <div class="layui-input-block">
                    <input class="layui-btn" type="submit" value="搜索" />
                </div>
            </div>
        </form>
        @using (Html.BeginForm("Release", "Questions", FormMethod.Post))
        {
            <div>

                <table class="table-hover gridtable">

                    <tr>
                        <th style="width:5%">
                            <input type="button" value="全选" class="layui-btn layui-btn-primary" onclick="ChooseAll()" />
                        </th>
                        @*<th>
                            序号
                        </th>*@

                        <th>
                            项目名称
                        </th>
                        <th>
                            课程名称
                        </th>
                        <th>
                            编号
                        </th>
                        <th>
                            发布类别
                        </th>
                        <th>
                            内容
                        </th>

                        <th>操作</th>
                    </tr>

                    @{

                        foreach (var item in Model)
                        {
                            <tr>
                                <td style="text-align:center">
                                    @if (item.Question.Status.Contains("C"))
                                    {
                                        <input type="checkbox" id="SelectQuestions" name="SelectQuestions" value="@item.Question.id" />
                                    }
                                </td>
                                @*<td>@rownum.ToString("00")</td>*@


                                <td>
                                    @Html.DisplayFor(modelItem => item.Project.ProjectName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Course.CourseName)
                                </td>

                                <td>@Html.DisplayFor(modelItem => item.Question.QuestionNum)</td>

                                <td>
                                    @if (item.Question.QuestionType.Contains("Q"))
                                    {
                                        @("问题")
                                    }
                                    @if (item.Question.QuestionType.Contains("N"))
                                    {
                                        @("通知")
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Question.QuestionDesc)
                                </td>

                                <td>
                                    @Html.ActionLink("详情", "Details", new { id = item.Question.id })

                                    @if (item.Question.Status.Contains("C"))
                                    {

                                        @Html.ActionLink("编辑", "Edit", new { id = item.Question.id })
                                        @Html.ActionLink("删除", "Delete", new { id = item.Question.id })
                                    }

                                </td>

                            </tr>
                            //rownum++;

                        }
                    }


                </table>
            </div>
            <h3 style="margin-bottom:12px">
                <input type="button" id="questionChoose" value="发布" class="layui-btn" />
                <input type="submit" id="questionSend" value="发布" class="layui-btn" onclick="GetId()" style="display:none;margin-left:20px" />
                <input type="hidden" id="tempString" name="tempString" />
            </h3>
            <div class="layui-form-item inline-show">
                <div class="layui-btn layui-btn-normal">@Html.ActionLink("添加", "Create")</div>
            </div>
                        }
        <div class="shared-pageList">
            每页 @Model.PageSize 条记录，共 @Model.PageCount 页，当前第 @Model.PageNumber 页
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, ProjectId, CourseId, QuestionDesc }))
        </div>
    </div>
        
    </div>






<script>
    //获取项目 再给子下拉框赋值
    function GetProjectId(id) {
        if (id == null) {
            return;
        }
        else {
            $("#CourseId").empty();
            $.ajax({
                url: "/Questions/BindCourse/" + id,
                type: "post",

                success: function (data) {
                    $("#CourseId").append("<option value=''>所有课程</option>")
                    $(data).each(function () {
                        $("#CourseId").append("<option value='" + this.Value + "'>" + this.Text + "</option>")
                    })
                }
            })
        }
    }


    function GetId() {
        var bb = "";
        var temp = "";
        var a = document.getElementsByName("SelectQuestions");
        for (var i = 0; i < a.length; i++) {
            if (a[i].checked) {
                temp = a[i].value;
                bb = bb + "," + temp;
            }
        }
        document.getElementById("tempString").value = bb
        .substring(1, bb.length);
    }

    function ChooseAll() {
        var a = document.getElementsByName("SelectQuestions");
        for (var i = 0; i < a.length; i++) {
            a[i].checked = true;
        }
    }

</script>